name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    env:
      TIPI_CACHE_FORCE_ENABLE: ON
      CMAKE_TIPI_PROVIDER_ENABLE: ON
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project 
        run: |
          tipi . -t linux-cxx17 --dont-upgrade --verbose --test all --use-cmakelists
